apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: vprofile/vprofileapp:V1
          ports:
            - name: vproapp-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vproapp-service    # Must match with what defined in application.properties
spec:
  ports:
    - port: 80
      targetPort: vproapp-port
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer